/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12-1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.an9elkiss.api.timedo.api;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;

import com.an9elkiss.api.timedo.command.TimeEntryCmd;
import com.an9elkiss.commons.command.ApiResponseCmd;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-04-28T09:59:07.066Z")

@Api(value = "time-entry", description = "the time-entry API")
public interface TimeEntryApi {

    @ApiOperation(value = "Add a new time entry record to record what you have done", nickname = "addTimeEntry", notes = "", tags={ "time-entry", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
	ResponseEntity<ApiResponseCmd> addTimeEntry(
			@ApiParam(value = "Date of the time entry", required = true) @RequestParam(value = "date", required = true) @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") Date date,
			@ApiParam(value = "Type of time entry", required = true) @RequestParam(value = "typeId", required = true) Integer typeId,
			@ApiParam(value = "Duration of time entry", required = true) @RequestParam(value = "duration", required = true) Integer duration,
			@ApiParam(value = "Comment of time entry") @RequestParam(value = "comment", required = false) String comment);


    @ApiOperation(value = "Deletes a time entry", nickname = "deleteTimeEntry", notes = "", tags={ "time-entry", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied") })
	ResponseEntity<ApiResponseCmd> deleteTimeEntry(
			@ApiParam(value = "Time entry id to delete", required = true) @PathVariable("id") Integer id);


	@ApiOperation(value = "Finds time entry by id", nickname = "findTimeEntryById", notes = "Finds time entry by id", response = TimeEntryCmd.class, tags = {
			"time-entry", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = TimeEntryCmd.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied") })
	ResponseEntity<ApiResponseCmd<TimeEntryCmd>> findTimeEntryById(
			@ApiParam(value = "ID of time entry that needs to be fetched", required = true) @PathVariable("id") Integer id);


    @ApiOperation(value = "Update an existing time entry", nickname = "updateTimeEntry", notes = "", tags={ "time-entry", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 405, message = "Validation exception") })
    ResponseEntity<ApiResponseCmd<TimeEntryCmd>> updateTimeEntry(
			@ApiParam(value = "ID of time entry that needs to be updated", required = true) @PathVariable("id") Integer id,
			@ApiParam(value = "Updated date of the time entry", required = true) @RequestParam(value = "date", required = true) @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") Date date,
			@ApiParam(value = "Updated type of time entry", required = true) @RequestParam(value = "typeId", required = true) Integer typeId,
			@ApiParam(value = "Updated duration of time entry", required = true) @RequestParam(value = "duration", required = true) Integer duration,
			@ApiParam(value = "Updated comment of time entry") @RequestParam(value = "comment", required = false) String comment);
}
